name: chat_hive_ai
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  cloud_firestore: ^4.16.0
  provider: ^6.1.2

  chat_hive_ai_core:
    path: "../chat_hive_ai_core"
  equatable: ^2.0.5
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1
  svg_flutter: ^0.0.1  
  google_generative_ai: ^0.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_markdown: ^0.7.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  

flutter_native_splash:
  android: true
  color: "#ffffff"
  image: "assets/app/logo_splash_chat_hive_ai_black.png" 
  color_dark: "#0C120C"
  image_dark: "assets/app/logo_splash_chat_hive_ai_white.png"

flutter_icons:
  image_path: "assets/app/logo_app_chat_hive_ai.png"
  android: "ic_launcher"
  background_color: "#ffffff"
  #adaptive_icon_background: "#ffffff"
  #adaptive_icon_foreground: "assets/app/logo_app_chat_hive_ai.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^3.0.0
  mocktail:


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/icons/
    - assets/images/logos/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

